// frontend/src/pages/CompanyProfile.tsx
import { useState, useEffect, FormEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import api from '../api/axios';
import { maskCNPJ, maskCPF, maskCEP, maskTel } from '../utils/masks';
import { ESTADOS_BR } from '../utils/constants';

interface CompanyData {
  razaoSocial: string;
  cnpj: string;
  inscricaoEstadual: string;
  endereco: string;
  cidade: string;
  estado: string;
  cep: string;
  representanteNome: string;
  representanteCpf: string;
  representanteCargo: string;
  localAssinatura: string;
  dataContrato: string;
}

interface AuxData {
  responsavelNome: string;
  responsavelTelefone: string;
  responsavelEmail: string;
  responsavelAniversario: string;
  pagamentoTipo: 'banco' | 'pix';
  banco: string;
  agencia: string;
  conta: string;
  tipoConta: string;
  pixTipo: string;
  pixChave: string;
  testemunhaNome: string;
  testemunhaCpf: string;
  testemunhaEmail: string;
}

const emptyCompany: CompanyData = {
  razaoSocial: '', cnpj: '', inscricaoEstadual: '', endereco: '', cidade: '', estado: '', cep: '',
  representanteNome: '', representanteCpf: '', representanteCargo: '', localAssinatura: '', dataContrato: '',
};

const emptyAux: AuxData = {
  responsavelNome: '', responsavelTelefone: '', responsavelEmail: '', responsavelAniversario: '',
  pagamentoTipo: 'pix', banco: '', agencia: '', conta: '', tipoConta: 'corrente',
  pixTipo: 'cpf', pixChave: '',
  testemunhaNome: '', testemunhaCpf: '', testemunhaEmail: '',
};

export default function CompanyProfile() {
  const { updateLocalUser } = useAuth();
  const navigate = useNavigate();
  const [step, setStep] = useState(1);
  const [company, setCompany] = useState<CompanyData>({ ...emptyCompany });
  const [aux, setAux] = useState<AuxData>({ ...emptyAux });
  const [loading, setLoading] = useState(false);
  const [loadingPage, setLoadingPage] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    api.get('/partner/profile').then(res => {
      const p = res.data;
      if (p.razaoSocial) {
        setCompany({
          razaoSocial: p.razaoSocial || '',
          cnpj: p.cnpj ? maskCNPJ(p.cnpj) : '',
          inscricaoEstadual: p.inscricaoEstadual || '',
          endereco: p.endereco || '',
          cidade: p.cidade || '',
          estado: p.estado || '',
          cep: p.cep ? maskCEP(p.cep) : '',
          representanteNome: p.representante?.nome || '',
          representanteCpf: p.representante?.cpf ? maskCPF(p.representante.cpf) : '',
          representanteCargo: p.representante?.cargo || '',
          localAssinatura: p.localAssinatura || '',
          dataContrato: p.dataContrato ? p.dataContrato.substring(0, 10) : '',
        });
      }
      if (p.responsavel) {
        setAux({
          responsavelNome: p.responsavel?.nome || '',
          responsavelTelefone: p.responsavel?.telefone ? maskTel(p.responsavel.telefone) : '',
          responsavelEmail: p.responsavel?.email || '',
          responsavelAniversario: p.responsavel?.aniversario ? p.responsavel.aniversario.substring(0, 10) : '',
          pagamentoTipo: p.pagamento?.tipo || 'pix',
          banco: p.pagamento?.banco || '',
          agencia: p.pagamento?.agencia || '',
          conta: p.pagamento?.conta || '',
          tipoConta: p.pagamento?.tipoConta || 'corrente',
          pixTipo: p.pagamento?.pixTipo || 'cpf',
          pixChave: p.pagamento?.pixChave || '',
          testemunhaNome: p.testemunha?.nome || '',
          testemunhaCpf: p.testemunha?.cpf ? maskCPF(p.testemunha.cpf) : '',
          testemunhaEmail: p.testemunha?.email || '',
        });
      }
    }).catch(() => {}).finally(() => setLoadingPage(false));
  }, []);

  function setC(field: keyof CompanyData, value: string) {
    setCompany(prev => ({ ...prev, [field]: value }));
  }

  function setA(field: keyof AuxData, value: string) {
    setAux(prev => ({ ...prev, [field]: value }));
  }

  async function handleStep1(e: FormEvent) {
    e.preventDefault();
    setError('');
    if (!company.razaoSocial || !company.cnpj || !company.endereco || !company.cidade || !company.estado || !company.cep) {
      setError('Preencha todos os campos obrigatórios da empresa.');
      return;
    }
    if (!company.representanteNome || !company.representanteCpf || !company.representanteCargo) {
      setError('Preencha os dados do representante legal.');
      return;
    }
    if (!company.localAssinatura || !company.dataContrato) {
      setError('Preencha o local e data do contrato.');
      return;
    }
    setLoading(true);
    try {
      await api.post('/partner/company', {
        razaoSocial: company.razaoSocial,
        cnpj: company.cnpj.replace(/\D/g, ''),
        inscricaoEstadual: company.inscricaoEstadual,
        endereco: company.endereco,
        cidade: company.cidade,
        estado: company.estado,
        cep: company.cep.replace(/\D/g, ''),
        representante: {
          nome: company.representanteNome,
          cpf: company.representanteCpf.replace(/\D/g, ''),
          cargo: company.representanteCargo,
        },
        localAssinatura: company.localAssinatura,
        dataContrato: company.dataContrato,
      });
      setStep(2);
      window.scrollTo(0, 0);
    } catch (err: any) {
      setError(err.response?.data?.error || 'Erro ao salvar dados da empresa.');
    } finally {
      setLoading(false);
    }
  }

  async function handleStep2(e: FormEvent) {
    e.preventDefault();
    setError('');
    if (!aux.responsavelNome || !aux.responsavelTelefone || !aux.responsavelEmail) {
      setError('Preencha os dados do responsável.');
      return;
    }
    if (!aux.testemunhaNome || !aux.testemunhaCpf || !aux.testemunhaEmail) {
      setError('Preencha os dados da testemunha.');
      return;
    }
    setLoading(true);
    try {
      const pagamento: any = { tipo: aux.pagamentoTipo };
      if (aux.pagamentoTipo === 'banco') {
        pagamento.banco = aux.banco;
        pagamento.agencia = aux.agencia;
        pagamento.conta = aux.conta;
        pagamento.tipoConta = aux.tipoConta;
      } else {
        pagamento.pixTipo = aux.pixTipo;
        pagamento.pixChave = aux.pixChave;
      }
      await api.put('/partner/auxiliary-data', {
        responsavel: {
          nome: aux.responsavelNome,
          telefone: aux.responsavelTelefone.replace(/\D/g, ''),
          email: aux.responsavelEmail,
          aniversario: aux.responsavelAniversario || undefined,
        },
        pagamento,
        testemunha: {
          nome: aux.testemunhaNome,
          cpf: aux.testemunhaCpf.replace(/\D/g, ''),
          email: aux.testemunhaEmail,
        },
      });
      updateLocalUser({ onboardingStep: 'contract' });
      navigate('/contract');
    } catch (err: any) {
      setError(err.response?.data?.error || 'Erro ao salvar dados auxiliares.');
    } finally {
      setLoading(false);
    }
  }

  if (loadingPage) {
    return (
      <div style={styles.wrap}>
        <div style={{ textAlign: 'center', padding: 60, color: '#888' }}>Carregando...</div>
      </div>
    );
  }

  return (
    <div style={styles.wrap}>
      <h1 style={styles.h1}>Cadastro da Empresa</h1>
      <p style={styles.sub}>Preencha os dados para gerar seu contrato de parceria.</p>

      {/* Step indicators */}
      <div style={styles.steps}>
        <div style={{ ...styles.stepItem, ...(step >= 1 ? styles.stepActive : {}) }}>
          <span style={styles.stepNum}>1</span>
          <span>Dados da Empresa</span>
        </div>
        <div style={styles.stepLine} />
        <div style={{ ...styles.stepItem, ...(step >= 2 ? styles.stepActive : {}) }}>
          <span style={styles.stepNum}>2</span>
          <span>Dados Auxiliares</span>
        </div>
      </div>

      {error && <div style={styles.error}>{error}</div>}

      {step === 1 && (
        <form onSubmit={handleStep1}>
          <div style={styles.card}>
            <h2 style={styles.h2}>Dados da Empresa</h2>
            <div style={styles.row}>
              <div style={styles.col}>
                <label style={styles.label}>Razão Social *</label>
                <input style={styles.input} value={company.razaoSocial} onChange={e => setC('razaoSocial', e.target.value)} placeholder="Razão Social da empresa" />
              </div>
              <div style={styles.col}>
                <label style={styles.label}>CNPJ *</label>
                <input style={styles.input} value={company.cnpj} onChange={e => setC('cnpj', maskCNPJ(e.target.value))} placeholder="00.000.000/0000-00" />
              </div>
            </div>
            <div style={styles.row}>
              <div style={styles.col}>
                <label style={styles.label}>Inscrição Estadual</label>
                <input style={styles.input} value={company.inscricaoEstadual} onChange={e => setC('inscricaoEstadual', e.target.value)} placeholder="Inscrição Estadual" />
              </div>
            </div>
            <div style={styles.row}>
              <div style={{ flex: 2 }}>
                <label style={styles.label}>Endereço *</label>
                <input style={styles.input} value={company.endereco} onChange={e => setC('endereco', e.target.value)} placeholder="Rua, número, complemento" />
              </div>
            </div>
            <div style={styles.row}>
              <div style={styles.col}>
                <label style={styles.label}>Cidade *</label>
                <input style={styles.input} value={company.cidade} onChange={e => setC('cidade', e.target.value)} placeholder="Cidade" />
              </div>
              <div style={styles.col}>
                <label style={styles.label}>Estado *</label>
                <select style={styles.input} value={company.estado} onChange={e => setC('estado', e.target.value)}>
                  <option value="">Selecione</option>
                  {ESTADOS_BR.map(uf => <option key={uf} value={uf}>{uf}</option>)}
                </select>
              </div>
              <div style={styles.col}>
                <label style={styles.label}>CEP *</label>
                <input style={styles.input} value={company.cep} onChange={e => setC('cep', maskCEP(e.target.value))} placeholder="00000-000" />
              </div>
            </div>
          </div>

          <div style={{ ...styles.card, marginTop: 20 }}>
            <h2 style={styles.h2}>Representante Legal</h2>
            <div style={styles.row}>
              <div style={styles.col}>
                <label style={styles.label}>Nome *</label>
                <input style={styles.input} value={company.representanteNome} onChange={e => setC('representanteNome', e.target.value)} placeholder="Nome completo" />
              </div>
              <div style={styles.col}>
                <label style={styles.label}>CPF *</label>
                <input style={styles.input} value={company.representanteCpf} onChange={e => setC('representanteCpf', maskCPF(e.target.value))} placeholder="000.000.000-00" />
              </div>
              <div style={styles.col}>
                <label style={styles.label}>Cargo *</label>
                <input style={styles.input} value={company.representanteCargo} onChange={e => setC('representanteCargo', e.target.value)} placeholder="Ex: Diretor" />
              </div>
            </div>
          </div>

          <div style={{ ...styles.card, marginTop: 20 }}>
            <h2 style={styles.h2}>Local e Data do Contrato</h2>
            <div style={styles.row}>
              <div style={styles.col}>
                <label style={styles.label}>Local de Assinatura *</label>
                <input style={styles.input} value={company.localAssinatura} onChange={e => setC('localAssinatura', e.target.value)} placeholder="Ex: São Paulo - SP" />
              </div>
              <div style={styles.col}>
                <label style={styles.label}>Data do Contrato *</label>
                <input style={styles.input} type="date" value={company.dataContrato} onChange={e => setC('dataContrato', e.target.value)} />
              </div>
            </div>
          </div>

          <div style={styles.btnRow}>
            <button type="submit" disabled={loading} style={styles.btn}>
              {loading ? 'Salvando...' : 'Próximo: Dados Auxiliares'}
            </button>
          </div>
        </form>
      )}

      {step === 2 && (
        <form onSubmit={handleStep2}>
          <div style={styles.card}>
            <h2 style={styles.h2}>Responsável pelo Contato</h2>
            <div style={styles.row}>
              <div style={styles.col}>
                <label style={styles.label}>Nome *</label>
                <input style={styles.input} value={aux.responsavelNome} onChange={e => setA('responsavelNome', e.target.value)} placeholder="Nome do responsável" />
              </div>
              <div style={styles.col}>
                <label style={styles.label}>Telefone *</label>
                <input style={styles.input} value={aux.responsavelTelefone} onChange={e => setA('responsavelTelefone', maskTel(e.target.value))} placeholder="(00) 00000-0000" />
              </div>
            </div>
            <div style={styles.row}>
              <div style={styles.col}>
                <label style={styles.label}>E-mail *</label>
                <input style={styles.input} type="email" value={aux.responsavelEmail} onChange={e => setA('responsavelEmail', e.target.value)} placeholder="email@empresa.com" />
              </div>
              <div style={styles.col}>
                <label style={styles.label}>Aniversário</label>
                <input style={styles.input} type="date" value={aux.responsavelAniversario} onChange={e => setA('responsavelAniversario', e.target.value)} />
              </div>
            </div>
          </div>

          <div style={{ ...styles.card, marginTop: 20 }}>
            <h2 style={styles.h2}>Dados de Pagamento</h2>
            <div style={styles.row}>
              <div style={styles.col}>
                <label style={styles.label}>Tipo de Pagamento</label>
                <div style={styles.toggleWrap}>
                  <button type="button" style={{ ...styles.toggleBtn, ...(aux.pagamentoTipo === 'banco' ? styles.toggleActive : {}) }} onClick={() => setA('pagamentoTipo', 'banco')}>
                    Conta Bancária
                  </button>
                  <button type="button" style={{ ...styles.toggleBtn, ...(aux.pagamentoTipo === 'pix' ? styles.toggleActive : {}) }} onClick={() => setA('pagamentoTipo', 'pix')}>
                    PIX
                  </button>
                </div>
              </div>
            </div>
            {aux.pagamentoTipo === 'banco' && (
              <>
                <div style={styles.row}>
                  <div style={styles.col}>
                    <label style={styles.label}>Banco</label>
                    <input style={styles.input} value={aux.banco} onChange={e => setA('banco', e.target.value)} placeholder="Nome do banco" />
                  </div>
                  <div style={styles.col}>
                    <label style={styles.label}>Agência</label>
                    <input style={styles.input} value={aux.agencia} onChange={e => setA('agencia', e.target.value)} placeholder="0000" />
                  </div>
                </div>
                <div style={styles.row}>
                  <div style={styles.col}>
                    <label style={styles.label}>Conta</label>
                    <input style={styles.input} value={aux.conta} onChange={e => setA('conta', e.target.value)} placeholder="00000-0" />
                  </div>
                  <div style={styles.col}>
                    <label style={styles.label}>Tipo de Conta</label>
                    <select style={styles.input} value={aux.tipoConta} onChange={e => setA('tipoConta', e.target.value)}>
                      <option value="corrente">Corrente</option>
                      <option value="poupanca">Poupança</option>
                    </select>
                  </div>
                </div>
              </>
            )}
            {aux.pagamentoTipo === 'pix' && (
              <div style={styles.row}>
                <div style={styles.col}>
                  <label style={styles.label}>Tipo da Chave PIX</label>
                  <select style={styles.input} value={aux.pixTipo} onChange={e => setA('pixTipo', e.target.value)}>
                    <option value="cpf">CPF</option>
                    <option value="cnpj">CNPJ</option>
                    <option value="email">E-mail</option>
                    <option value="telefone">Telefone</option>
                    <option value="aleatoria">Chave Aleatória</option>
                  </select>
                </div>
                <div style={styles.col}>
                  <label style={styles.label}>Chave PIX</label>
                  <input style={styles.input} value={aux.pixChave} onChange={e => setA('pixChave', e.target.value)} placeholder="Sua chave PIX" />
                </div>
              </div>
            )}
          </div>

          <div style={{ ...styles.card, marginTop: 20 }}>
            <h2 style={styles.h2}>Testemunha</h2>
            <div style={styles.row}>
              <div style={styles.col}>
                <label style={styles.label}>Nome *</label>
                <input style={styles.input} value={aux.testemunhaNome} onChange={e => setA('testemunhaNome', e.target.value)} placeholder="Nome completo" />
              </div>
              <div style={styles.col}>
                <label style={styles.label}>CPF *</label>
                <input style={styles.input} value={aux.testemunhaCpf} onChange={e => setA('testemunhaCpf', maskCPF(e.target.value))} placeholder="000.000.000-00" />
              </div>
              <div style={styles.col}>
                <label style={styles.label}>E-mail *</label>
                <input style={styles.input} type="email" value={aux.testemunhaEmail} onChange={e => setA('testemunhaEmail', e.target.value)} placeholder="email@exemplo.com" />
              </div>
            </div>
          </div>

          <div style={styles.btnRow}>
            <button type="button" style={styles.btnOutline} onClick={() => { setStep(1); setError(''); window.scrollTo(0, 0); }}>
              Voltar
            </button>
            <button type="submit" disabled={loading} style={styles.btn}>
              {loading ? 'Salvando...' : 'Salvar e Ir para Contrato'}
            </button>
          </div>
        </form>
      )}
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  wrap: { maxWidth: 800, margin: '0 auto', padding: '32px 24px 80px' },
  h1: { fontSize: 24, color: '#1B5E8C', margin: 0 },
  sub: { color: '#666', margin: '4px 0 24px' },
  steps: { display: 'flex', alignItems: 'center', gap: 12, marginBottom: 24 },
  stepItem: { display: 'flex', alignItems: 'center', gap: 8, padding: '8px 16px', borderRadius: 8, background: '#F2F3F4', color: '#888', fontSize: 14, fontWeight: 600 },
  stepActive: { background: '#EAF2F8', color: '#1B5E8C' },
  stepNum: { width: 28, height: 28, borderRadius: '50%', background: '#D8DEE4', color: '#fff', display: 'inline-flex', alignItems: 'center', justifyContent: 'center', fontSize: 13, fontWeight: 700 },
  stepLine: { flex: 1, height: 2, background: '#D8DEE4' },
  card: { background: '#fff', border: '1px solid #D8DEE4', borderRadius: 12, padding: 24 },
  h2: { fontSize: 16, color: '#1B5E8C', margin: '0 0 16px', paddingBottom: 12, borderBottom: '1px solid #F2F3F4' },
  row: { display: 'flex', gap: 16, marginBottom: 16, flexWrap: 'wrap' as const },
  col: { flex: 1, minWidth: 200 },
  label: { display: 'block', fontSize: 12, fontWeight: 600, color: '#5A6672', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 6 },
  input: { width: '100%', padding: '10px 14px', border: '1.5px solid #D8DEE4', borderRadius: 8, fontSize: 14, background: '#F7F9FB', boxSizing: 'border-box' as const },
  btnRow: { display: 'flex', justifyContent: 'flex-end', gap: 12, marginTop: 24 },
  btn: { padding: '12px 32px', background: '#1B5E8C', color: '#fff', border: 'none', borderRadius: 10, fontSize: 15, fontWeight: 700, cursor: 'pointer' },
  btnOutline: { padding: '12px 32px', background: '#fff', color: '#1B5E8C', border: '2px solid #1B5E8C', borderRadius: 10, fontSize: 15, fontWeight: 700, cursor: 'pointer' },
  error: { background: '#FDEDEC', color: '#C0392B', padding: '10px 14px', borderRadius: 8, fontSize: 13, marginBottom: 16 },
  toggleWrap: { display: 'flex', gap: 0, borderRadius: 8, overflow: 'hidden', border: '1.5px solid #D8DEE4' },
  toggleBtn: { flex: 1, padding: '10px 16px', border: 'none', background: '#F7F9FB', fontSize: 13, fontWeight: 600, color: '#888', cursor: 'pointer' },
  toggleActive: { background: '#1B5E8C', color: '#fff' },
};

// frontend/src/app/pages/company-profile/company-profile.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { ApiService } from '../../services/api.service';
import { ESTADOS_BR } from '../../models/interfaces';

@Component({
  selector: 'app-company-profile',
  template: `
    <div class="page-wrap">
      <div class="page-header">
        <h1>Dados da Empresa</h1>
        <p>Preencha as informações da sua empresa para gerar o contrato de parceria.</p>
        <div class="steps">
          <span class="step active">1. Dados da Empresa</span>
          <span class="step">2. Dados Auxiliares</span>
          <span class="step">3. Contrato</span>
        </div>
      </div>

      <!-- Step 1: Company Data -->
      <div *ngIf="step === 1">
        <div class="card">
          <h2>Identificação da Empresa</h2>
          <form [formGroup]="companyForm">
            <div class="field"><label>Razão Social *</label>
              <input formControlName="razaoSocial" placeholder="Razão social completa">
            </div>
            <div class="row">
              <div class="field"><label>CNPJ *</label>
                <input formControlName="cnpj" placeholder="00.000.000/0000-00" maxlength="18" (input)="maskCNPJ($event)">
              </div>
              <div class="field"><label>Inscr. Estadual</label>
                <input formControlName="inscricaoEstadual" placeholder="Isento ou número">
              </div>
            </div>
            <div class="field"><label>Endereço Completo *</label>
              <input formControlName="endereco" placeholder="Rua, número, complemento, bairro">
            </div>
            <div class="row-3">
              <div class="field"><label>Cidade *</label><input formControlName="cidade"></div>
              <div class="field"><label>Estado *</label>
                <select formControlName="estado">
                  <option value="">Selecione</option>
                  <option *ngFor="let uf of estados" [value]="uf">{{uf}}</option>
                </select>
              </div>
              <div class="field"><label>CEP *</label>
                <input formControlName="cep" placeholder="00000-000" maxlength="9" (input)="maskCEP($event)">
              </div>
            </div>

            <h2 style="margin-top:28px;">Representante Legal</h2>
            <div formGroupName="representante">
              <div class="field"><label>Nome Completo *</label><input formControlName="nome"></div>
              <div class="row">
                <div class="field"><label>CPF *</label>
                  <input formControlName="cpf" placeholder="000.000.000-00" maxlength="14" (input)="maskCPF($event)">
                </div>
                <div class="field"><label>Cargo *</label><input formControlName="cargo" placeholder="Ex: Sócio-Administrador"></div>
              </div>
            </div>

            <div class="row" style="margin-top:16px;">
              <div class="field"><label>Local da Assinatura</label><input formControlName="localAssinatura" placeholder="Ex: São Paulo/SP"></div>
              <div class="field"><label>Data do Contrato</label><input type="date" formControlName="dataContrato"></div>
            </div>
          </form>
        </div>
        <div class="actions">
          <button class="btn-primary" (click)="saveCompany()" [disabled]="saving">
            {{ saving ? 'Salvando...' : 'Continuar →' }}
          </button>
        </div>
      </div>

      <!-- Step 2: Auxiliary Data -->
      <div *ngIf="step === 2">
        <div class="card internal">
          <h2>Dados do Responsável <span class="badge">Uso Interno</span></h2>
          <form [formGroup]="auxForm">
            <div formGroupName="responsavel">
              <div class="field"><label>Nome *</label><input formControlName="nome"></div>
              <div class="row">
                <div class="field"><label>Telefone / WhatsApp *</label>
                  <input formControlName="telefone" placeholder="(00) 00000-0000" maxlength="15" (input)="maskTel($event)">
                </div>
                <div class="field"><label>E-mail *</label><input type="email" formControlName="email"></div>
              </div>
              <div class="field" style="max-width:220px;"><label>Aniversário *</label><input type="date" formControlName="aniversario"></div>
            </div>

            <h2 style="margin-top:28px;">Dados para Pagamento <span class="badge">Uso Interno</span></h2>
            <div class="toggle-bar">
              <button type="button" [class.active]="pagTipo==='banco'" (click)="pagTipo='banco'">Conta Bancária</button>
              <button type="button" [class.active]="pagTipo==='pix'" (click)="pagTipo='pix'">Chave PIX</button>
            </div>
            <div formGroupName="pagamento">
              <div *ngIf="pagTipo==='banco'">
                <div class="field"><label>Banco *</label><input formControlName="banco" placeholder="Ex: Itaú, Nubank"></div>
                <div class="row">
                  <div class="field"><label>Agência *</label><input formControlName="agencia"></div>
                  <div class="field"><label>Conta *</label><input formControlName="conta"></div>
                </div>
              </div>
              <div *ngIf="pagTipo==='pix'">
                <div class="field"><label>Chave PIX *</label><input formControlName="chavePix" placeholder="CPF, CNPJ, e-mail, telefone ou chave aleatória"></div>
              </div>
            </div>

            <h2 style="margin-top:28px;">Testemunha do Contrato</h2>
            <div formGroupName="testemunha">
              <div class="field"><label>Nome Completo *</label><input formControlName="nome"></div>
              <div class="row">
                <div class="field"><label>CPF *</label>
                  <input formControlName="cpf" placeholder="000.000.000-00" maxlength="14" (input)="maskCPFTest($event)">
                </div>
                <div class="field"><label>E-mail *</label><input type="email" formControlName="email"></div>
              </div>
            </div>
          </form>
        </div>
        <div class="actions">
          <button class="btn-secondary" (click)="step=1">← Voltar</button>
          <button class="btn-primary" (click)="saveAuxiliary()" [disabled]="saving">
            {{ saving ? 'Salvando...' : 'Continuar para o Contrato →' }}
          </button>
        </div>
      </div>

      <div class="error-msg" *ngIf="errorMsg">{{ errorMsg }}</div>
    </div>
  `,
  styles: [`
    .page-wrap { max-width:720px; margin:0 auto; padding:32px 24px 80px; }
    .page-header { margin-bottom:32px; }
    .page-header h1 { font-size:24px; color:#1B5E8C; margin:0 0 4px; }
    .page-header p { color:#666; font-size:14px; margin:0; }
    .steps { display:flex; gap:8px; margin-top:16px; }
    .step { font-size:12px; padding:6px 14px; border-radius:20px; background:#F2F3F4; color:#888; font-weight:600; }
    .step.active { background:#1B5E8C; color:#fff; }
    .card { background:#fff; border:1px solid #D8DEE4; border-radius:12px; padding:32px; margin-bottom:16px; box-shadow:0 1px 3px rgba(0,0,0,0.04); }
    .card.internal { border-left:4px solid #F39C12; }
    h2 { font-size:16px; color:#1B5E8C; margin:0 0 20px; padding-bottom:10px; border-bottom:2px solid #EAF2F8; }
    .badge { background:#FEF3E2; color:#B7791F; font-size:10px; padding:2px 8px; border-radius:10px; margin-left:8px; vertical-align:middle; }
    .field { margin-bottom:16px; }
    .field label { display:block; font-size:12px; font-weight:600; color:#5A6672; text-transform:uppercase; letter-spacing:0.5px; margin-bottom:5px; }
    .field input, .field select { width:100%; padding:10px 14px; border:1.5px solid #D8DEE4; border-radius:8px; font-size:14px; background:#F7F9FB; box-sizing:border-box; }
    .field input:focus, .field select:focus { outline:none; border-color:#1B5E8C; background:#fff; box-shadow:0 0 0 3px rgba(27,94,140,0.1); }
    .row { display:grid; grid-template-columns:1fr 1fr; gap:14px; }
    .row-3 { display:grid; grid-template-columns:1fr 1fr 1fr; gap:14px; }
    .toggle-bar { display:flex; gap:8px; margin-bottom:16px; }
    .toggle-bar button { flex:1; padding:10px; border:2px solid #D8DEE4; border-radius:8px; background:#F7F9FB; font-size:14px; font-weight:600; color:#888; cursor:pointer; }
    .toggle-bar button.active { border-color:#1B5E8C; background:#EAF2F8; color:#1B5E8C; }
    .actions { display:flex; gap:12px; justify-content:flex-end; margin-top:8px; }
    .btn-primary { padding:12px 32px; background:#1B5E8C; color:#fff; border:none; border-radius:10px; font-size:15px; font-weight:700; cursor:pointer; }
    .btn-primary:hover { background:#134263; }
    .btn-primary:disabled { opacity:0.7; }
    .btn-secondary { padding:12px 32px; background:#fff; color:#1B5E8C; border:2px solid #1B5E8C; border-radius:10px; font-size:15px; font-weight:600; cursor:pointer; }
    .error-msg { background:#FDEDEC; color:#C0392B; padding:12px; border-radius:8px; font-size:13px; margin-top:12px; }
    @media (max-width:640px) { .row,.row-3 { grid-template-columns:1fr; } }
  `]
})
export class CompanyProfileComponent implements OnInit {
  estados = ESTADOS_BR;
  step = 1;
  saving = false;
  errorMsg = '';
  pagTipo: 'banco' | 'pix' = 'pix';

  companyForm: FormGroup;
  auxForm: FormGroup;

  constructor(private fb: FormBuilder, private api: ApiService, private auth: AuthService, private router: Router) {
    this.companyForm = this.fb.group({
      razaoSocial: ['', [Validators.required, Validators.minLength(3)]],
      cnpj: ['', [Validators.required, Validators.pattern(/^\d{2}\.\d{3}\.\d{3}\/\d{4}-\d{2}$/)]],
      inscricaoEstadual: ['Isento'],
      endereco: ['', Validators.required],
      cidade: ['', Validators.required],
      estado: ['', Validators.required],
      cep: ['', [Validators.required, Validators.pattern(/^\d{5}-\d{3}$/)]],
      representante: this.fb.group({
        nome: ['', Validators.required],
        cpf: ['', [Validators.required, Validators.pattern(/^\d{3}\.\d{3}\.\d{3}-\d{2}$/)]],
        cargo: ['', Validators.required]
      }),
      localAssinatura: [''],
      dataContrato: [new Date().toISOString().split('T')[0]]
    });

    this.auxForm = this.fb.group({
      responsavel: this.fb.group({
        nome: ['', Validators.required],
        telefone: ['', Validators.required],
        email: ['', [Validators.required, Validators.email]],
        aniversario: ['', Validators.required]
      }),
      pagamento: this.fb.group({
        tipo: ['pix'],
        banco: [''], agencia: [''], conta: [''], chavePix: ['']
      }),
      testemunha: this.fb.group({
        nome: ['', Validators.required],
        cpf: ['', [Validators.required, Validators.pattern(/^\d{3}\.\d{3}\.\d{3}-\d{2}$/)]],
        email: ['', [Validators.required, Validators.email]]
      })
    });
  }

  ngOnInit() {
    this.api.getProfile().subscribe({
      next: (res: any) => {
        if (res.company) {
          this.companyForm.patchValue(res.company);
          if (res.company.representante) this.companyForm.get('representante')?.patchValue(res.company.representante);
        }
        if (res.user?.responsavel?.nome) {
          this.auxForm.get('responsavel')?.patchValue(res.user.responsavel);
        }
        if (res.user?.testemunha?.nome) {
          this.auxForm.get('testemunha')?.patchValue(res.user.testemunha);
        }
        if (res.user?.pagamento) {
          this.auxForm.get('pagamento')?.patchValue(res.user.pagamento);
          this.pagTipo = res.user.pagamento.tipo || 'pix';
        }
      },
      error: () => {}
    });
  }

  saveCompany() {
    if (this.companyForm.invalid) { this.errorMsg = 'Preencha todos os campos obrigatórios.'; return; }
    this.saving = true; this.errorMsg = '';
    this.api.saveCompany(this.companyForm.value).subscribe({
      next: () => { this.saving = false; this.step = 2; window.scrollTo(0, 0); },
      error: (err) => { this.saving = false; this.errorMsg = err.error?.error || 'Erro ao salvar.'; }
    });
  }

  saveAuxiliary() {
    this.auxForm.get('pagamento')?.patchValue({ tipo: this.pagTipo });
    this.saving = true; this.errorMsg = '';
    this.api.saveAuxiliaryData(this.auxForm.value).subscribe({
      next: () => {
        this.saving = false;
        this.auth.updateLocalUser({ onboardingStep: 'contract' });
        this.router.navigate(['/contract']);
      },
      error: (err) => { this.saving = false; this.errorMsg = err.error?.error || 'Erro ao salvar.'; }
    });
  }

  // Masks
  maskCNPJ(e: Event) { const t = e.target as HTMLInputElement; let v = t.value.replace(/\D/g,'').slice(0,14); v=v.replace(/^(\d{2})(\d)/,'$1.$2').replace(/^(\d{2})\.(\d{3})(\d)/,'$1.$2.$3').replace(/\.(\d{3})(\d)/,'.$1/$2').replace(/(\d{4})(\d)/,'$1-$2'); t.value=v; this.companyForm.get('cnpj')?.setValue(v); }
  maskCPF(e: Event) { const t = e.target as HTMLInputElement; let v = t.value.replace(/\D/g,'').slice(0,11); v=v.replace(/^(\d{3})(\d)/,'$1.$2').replace(/^(\d{3})\.(\d{3})(\d)/,'$1.$2.$3').replace(/\.(\d{3})(\d)/,'.$1-$2'); t.value=v; this.companyForm.get('representante.cpf')?.setValue(v); }
  maskCEP(e: Event) { const t = e.target as HTMLInputElement; let v = t.value.replace(/\D/g,'').slice(0,8); t.value=v.replace(/^(\d{5})(\d)/,'$1-$2'); this.companyForm.get('cep')?.setValue(t.value); }
  maskTel(e: Event) { const t = e.target as HTMLInputElement; let v = t.value.replace(/\D/g,'').slice(0,11); if(v.length>6)v=v.replace(/^(\d{2})(\d{5})(\d)/,'($1) $2-$3'); else if(v.length>2)v=v.replace(/^(\d{2})(\d)/,'($1) $2'); t.value=v; this.auxForm.get('responsavel.telefone')?.setValue(v); }
  maskCPFTest(e: Event) { const t = e.target as HTMLInputElement; let v = t.value.replace(/\D/g,'').slice(0,11); v=v.replace(/^(\d{3})(\d)/,'$1.$2').replace(/^(\d{3})\.(\d{3})(\d)/,'$1.$2.$3').replace(/\.(\d{3})(\d)/,'.$1-$2'); t.value=v; this.auxForm.get('testemunha.cpf')?.setValue(v); }
}
