// frontend/src/pages/Contract.tsx
import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import api from '../api/axios';

type ContractStatus = 'not_generated' | 'pending_signature' | 'signed' | 'error';

export default function Contract() {
  const { updateLocalUser } = useAuth();
  const navigate = useNavigate();
  const [status, setStatus] = useState<ContractStatus>('not_generated');
  const [loading, setLoading] = useState(true);
  const [signing, setSigning] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [confirming, setConfirming] = useState(false);
  const [error, setError] = useState('');
  const [success, setSuccess] = useState(false);
  const [signWarning, setSignWarning] = useState(false);

  useEffect(() => {
    checkStatus();
  }, []);

  async function checkStatus() {
    setLoading(true);
    try {
      const res = await api.get('/contract/status');
      const s = res.data.status;
      setStatus(s);
      if (s === 'signed') {
        updateLocalUser({ onboardingStep: 'active' });
      }
    } catch {
      setStatus('not_generated');
    } finally {
      setLoading(false);
    }
  }

  async function handleDownload() {
    setDownloading(true);
    setError('');
    try {
      const res = await api.get('/contract/pdf', { responseType: 'blob' });
      const url = window.URL.createObjectURL(new Blob([res.data], { type: 'application/pdf' }));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', 'contrato-parceria.pdf');
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (err: any) {
      setError(err.response?.data?.error || 'Erro ao baixar o PDF.');
    } finally {
      setDownloading(false);
    }
  }

  async function handleSign() {
    setSigning(true);
    setError('');
    setSuccess(false);
    setSignWarning(false);
    try {
      const res = await api.post('/contract/generate-and-sign');
      if (res.data.signed) {
        setSuccess(true);
        setStatus('signed');
        updateLocalUser({ onboardingStep: 'active' });
        setTimeout(() => navigate('/dashboard'), 3000);
      } else {
        setSignWarning(true);
        setStatus('pending_signature');
      }
    } catch (err: any) {
      setError(err.response?.data?.error || 'Erro ao assinar o contrato.');
    } finally {
      setSigning(false);
    }
  }

  async function handleConfirm() {
    setConfirming(true);
    setError('');
    try {
      await api.post('/contract/confirm-signed');
      setStatus('signed');
      setSuccess(true);
      updateLocalUser({ onboardingStep: 'active' });
      setTimeout(() => navigate('/dashboard'), 3000);
    } catch (err: any) {
      setError(err.response?.data?.error || 'Contrato ainda não foi assinado por todas as partes.');
    } finally {
      setConfirming(false);
    }
  }

  if (loading) {
    return (
      <div style={styles.wrap}>
        <div style={{ textAlign: 'center', padding: 60, color: '#888' }}>Carregando status do contrato...</div>
      </div>
    );
  }

  if (status === 'signed' || success) {
    return (
      <div style={styles.wrap}>
        <div style={styles.successCard}>
          <span style={{ fontSize: 56, color: '#27AE60' }}>&#10003;</span>
          <h1 style={{ color: '#27AE60', margin: '16px 0 8px', fontSize: 24 }}>Contrato Assinado!</h1>
          <p style={{ color: '#666', fontSize: 15, lineHeight: 1.6 }}>
            Seu contrato de parceria foi assinado com sucesso.
            Você será redirecionado para o painel em instantes.
          </p>
          <button style={styles.btn} onClick={() => navigate('/dashboard')}>
            Ir para o Painel
          </button>
        </div>
      </div>
    );
  }

  return (
    <div style={styles.wrap}>
      <h1 style={styles.h1}>Contrato de Parceria</h1>
      <p style={styles.sub}>Revise e assine seu contrato para ativar sua conta de parceiro.</p>

      {error && <div style={styles.error}>{error}</div>}

      {signWarning && (
        <div style={styles.warningCard}>
          <h3 style={{ color: '#F39C12', margin: '0 0 8px' }}>Assinatura Pendente</h3>
          <p style={{ color: '#666', fontSize: 14, margin: '0 0 12px' }}>
            O contrato foi enviado para assinatura digital. Verifique seu e-mail para assinar o documento.
            Após assinar, clique no botão abaixo para confirmar.
          </p>
          <div style={{ display: 'flex', gap: 12 }}>
            <button style={styles.btnOutline} onClick={checkStatus} disabled={loading}>
              Verificar Status
            </button>
            <button style={styles.btn} onClick={handleConfirm} disabled={confirming}>
              {confirming ? 'Confirmando...' : 'Confirmar Assinatura'}
            </button>
          </div>
        </div>
      )}

      <div style={styles.card}>
        <h2 style={styles.h2}>Ações do Contrato</h2>

        <div style={styles.actionRow}>
          <div style={styles.actionInfo}>
            <h3 style={styles.actionTitle}>Baixar Contrato (PDF)</h3>
            <p style={styles.actionDesc}>Faça o download do contrato para revisão antes de assinar.</p>
          </div>
          <button style={styles.btnOutline} onClick={handleDownload} disabled={downloading}>
            {downloading ? 'Baixando...' : 'Baixar PDF'}
          </button>
        </div>

        <div style={styles.divider} />

        <div style={styles.actionRow}>
          <div style={styles.actionInfo}>
            <h3 style={styles.actionTitle}>Assinar Contrato Digitalmente</h3>
            <p style={styles.actionDesc}>
              Ao clicar, o contrato será gerado e enviado para assinatura digital.
              Você receberá um e-mail com o link para assinar.
            </p>
          </div>
          <button style={styles.btn} onClick={handleSign} disabled={signing}>
            {signing ? 'Processando...' : 'Assinar Contrato'}
          </button>
        </div>

        {status === 'pending_signature' && !signWarning && (
          <>
            <div style={styles.divider} />
            <div style={styles.actionRow}>
              <div style={styles.actionInfo}>
                <h3 style={styles.actionTitle}>Já assinou o contrato?</h3>
                <p style={styles.actionDesc}>Se você já assinou o documento por e-mail, clique para confirmar e ativar sua conta.</p>
              </div>
              <div style={{ display: 'flex', gap: 12 }}>
                <button style={styles.btnOutline} onClick={checkStatus} disabled={loading}>
                  Verificar Status
                </button>
                <button style={styles.btn} onClick={handleConfirm} disabled={confirming}>
                  {confirming ? 'Confirmando...' : 'Confirmar Assinatura'}
                </button>
              </div>
            </div>
          </>
        )}
      </div>

      <div style={styles.infoCard}>
        <h3 style={{ margin: '0 0 8px', color: '#1B5E8C', fontSize: 14 }}>Sobre o processo de assinatura</h3>
        <ul style={{ margin: 0, paddingLeft: 20, color: '#666', fontSize: 13, lineHeight: 1.8 }}>
          <li>O contrato é gerado automaticamente com os dados informados no cadastro.</li>
          <li>A assinatura digital tem validade jurídica conforme a legislação brasileira.</li>
          <li>Após a assinatura, sua conta será ativada e você poderá começar a indicar clientes.</li>
          <li>Uma cópia do contrato assinado será enviada para o seu e-mail.</li>
        </ul>
      </div>
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  wrap: { maxWidth: 800, margin: '0 auto', padding: '32px 24px 80px' },
  h1: { fontSize: 24, color: '#1B5E8C', margin: 0 },
  sub: { color: '#666', margin: '4px 0 24px' },
  card: { background: '#fff', border: '1px solid #D8DEE4', borderRadius: 12, padding: 24, marginBottom: 20 },
  h2: { fontSize: 16, color: '#1B5E8C', margin: '0 0 20px', paddingBottom: 12, borderBottom: '1px solid #F2F3F4' },
  actionRow: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 20, flexWrap: 'wrap' as const },
  actionInfo: { flex: 1, minWidth: 250 },
  actionTitle: { margin: '0 0 4px', fontSize: 15, color: '#2A2A2A', fontWeight: 600 },
  actionDesc: { margin: 0, fontSize: 13, color: '#888', lineHeight: 1.5 },
  divider: { height: 1, background: '#F2F3F4', margin: '20px 0' },
  btn: { padding: '12px 28px', background: '#1B5E8C', color: '#fff', border: 'none', borderRadius: 10, fontSize: 14, fontWeight: 700, cursor: 'pointer', whiteSpace: 'nowrap' as const },
  btnOutline: { padding: '12px 28px', background: '#fff', color: '#1B5E8C', border: '2px solid #1B5E8C', borderRadius: 10, fontSize: 14, fontWeight: 700, cursor: 'pointer', whiteSpace: 'nowrap' as const },
  error: { background: '#FDEDEC', color: '#C0392B', padding: '10px 14px', borderRadius: 8, fontSize: 13, marginBottom: 16 },
  successCard: { background: '#fff', border: '2px solid #27AE60', borderRadius: 16, padding: '48px 40px', textAlign: 'center' as const, maxWidth: 500, margin: '60px auto' },
  warningCard: { background: '#FEF9E7', border: '1px solid #F9E79F', borderRadius: 12, padding: 20, marginBottom: 20 },
  infoCard: { background: '#EAF2F8', border: '1px solid #D4E6F1', borderRadius: 12, padding: 20 },
};

// frontend/src/app/pages/contract/contract.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { ApiService } from '../../services/api.service';

@Component({
  selector: 'app-contract',
  template: `
    <div class="page-wrap">
      <div class="page-header">
        <h1>Contrato de Parceria</h1>
        <p>Revise e assine o contrato de indicação comercial.</p>
      </div>

      <div class="card" *ngIf="!sent">
        <div class="contract-info">
          <h2>Contrato de Parceria de Indicação Comercial</h2>
          <p>Ao clicar em "Assinar Contrato", o documento será enviado para assinatura digital via <strong>D4Sign</strong> para:</p>
          <ul>
            <li>Mais Chat Tecnologia (contratante)</li>
            <li>Sua empresa (parceiro)</li>
            <li>Testemunha informada no cadastro</li>
          </ul>
          <p>Todos receberão um e-mail da D4Sign com o link para assinatura.</p>
        </div>
        <div class="actions">
          <button class="btn-secondary" (click)="downloadPdf()" [disabled]="downloading">
            {{ downloading ? 'Gerando...' : '📄 Baixar PDF para Revisão' }}
          </button>
          <button class="btn-primary" (click)="signContract()" [disabled]="signing">
            {{ signing ? 'Enviando...' : '✍️ Assinar Contrato via D4Sign' }}
          </button>
        </div>
      </div>

      <div class="card success-card" *ngIf="sent && !fallback">
        <span class="icon">✓</span>
        <h2>Contrato Enviado para Assinatura!</h2>
        <p>Verifique o e-mail dos signatários para acessar o link de assinatura da D4Sign.</p>
        <p class="info">Após todas as assinaturas, seu acesso ao painel de indicações será liberado automaticamente.</p>
        <button class="btn-primary" (click)="checkStatus()">Verificar Status</button>
        <button class="btn-secondary" style="margin-top:8px;" (click)="confirmManual()">Já assinei, liberar acesso</button>
      </div>

      <div class="card warning-card" *ngIf="sent && fallback">
        <span class="icon">⚠️</span>
        <h2>PDF Gerado com Sucesso</h2>
        <p>A integração com D4Sign está temporariamente indisponível. O PDF do contrato foi baixado.</p>
        <p class="info">Assine o documento e envie para <strong>admin&#64;maischat.com</strong>.</p>
        <button class="btn-primary" (click)="confirmManual()">Já enviei o contrato assinado</button>
      </div>

      <div class="error-msg" *ngIf="errorMsg">{{ errorMsg }}</div>
    </div>
  `,
  styles: [`
    .page-wrap { max-width:640px; margin:0 auto; padding:32px 24px 80px; }
    .page-header h1 { font-size:24px; color:#1B5E8C; margin:0 0 4px; }
    .page-header p { color:#666; font-size:14px; margin:0 0 24px; }
    .card { background:#fff; border:1px solid #D8DEE4; border-radius:12px; padding:32px; box-shadow:0 1px 3px rgba(0,0,0,0.04); }
    .success-card { text-align:center; border-color:#27AE60; }
    .success-card .icon { color:#27AE60; font-size:48px; }
    .success-card h2 { color:#27AE60; }
    .warning-card { text-align:center; border-color:#F39C12; }
    .warning-card .icon { font-size:48px; }
    .warning-card h2 { color:#F39C12; }
    h2 { font-size:18px; color:#1B5E8C; margin:0 0 12px; }
    p { color:#555; line-height:1.6; margin-bottom:8px; }
    .info { background:#EAF2F8; padding:12px; border-radius:8px; font-size:13px; color:#134263; margin-top:12px; }
    ul { padding-left:20px; margin:8px 0 16px; color:#555; }
    ul li { margin-bottom:4px; font-size:14px; }
    .actions { display:flex; gap:12px; margin-top:24px; flex-wrap:wrap; }
    .btn-primary { padding:12px 28px; background:#1B5E8C; color:#fff; border:none; border-radius:10px; font-size:15px; font-weight:700; cursor:pointer; }
    .btn-primary:hover { background:#134263; }
    .btn-primary:disabled { opacity:0.7; }
    .btn-secondary { padding:12px 28px; background:#fff; color:#1B5E8C; border:2px solid #1B5E8C; border-radius:10px; font-size:14px; font-weight:600; cursor:pointer; }
    .error-msg { background:#FDEDEC; color:#C0392B; padding:12px; border-radius:8px; font-size:13px; margin-top:16px; }
  `]
})
export class ContractComponent implements OnInit {
  sent = false;
  fallback = false;
  signing = false;
  downloading = false;
  errorMsg = '';

  constructor(private api: ApiService, private auth: AuthService, private router: Router) {}

  ngOnInit() {
    // Check if already sent
    this.api.getContractStatus().subscribe({
      next: (res: any) => {
        if (res.status !== 'not_sent' && res.status !== 'unavailable') { this.sent = true; }
      }
    });
  }

  downloadPdf() {
    this.downloading = true;
    this.api.downloadContractPdf().subscribe({
      next: (blob: Blob) => {
        this.downloading = false;
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = 'Contrato_Parceria_Indicacao_MaisChat.pdf';
        a.click();
        window.URL.revokeObjectURL(url);
      },
      error: () => { this.downloading = false; this.errorMsg = 'Erro ao gerar PDF.'; }
    });
  }

  signContract() {
    this.signing = true; this.errorMsg = '';
    this.api.generateAndSign().subscribe({
      next: (res: any) => {
        this.signing = false;
        this.sent = true;
        this.fallback = !!res.fallback;
        if (res.fallback && res.pdfBase64) {
          // Download fallback PDF
          const binary = atob(res.pdfBase64);
          const bytes = new Uint8Array(binary.length);
          for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
          const blob = new Blob([bytes], { type: 'application/pdf' });
          const url = window.URL.createObjectURL(blob);
          const a = document.createElement('a');
          a.href = url; a.download = 'Contrato_Parceria.pdf'; a.click();
          window.URL.revokeObjectURL(url);
        }
      },
      error: (err) => { this.signing = false; this.errorMsg = err.error?.error || 'Erro ao enviar contrato.'; }
    });
  }

  checkStatus() {
    this.api.getContractStatus().subscribe({
      next: (res: any) => {
        if (res.status?.statusId === '4') {
          this.auth.updateLocalUser({ onboardingStep: 'active' });
          this.router.navigate(['/dashboard']);
        } else {
          this.errorMsg = 'Aguardando assinaturas. Verifique novamente em breve.';
          setTimeout(() => this.errorMsg = '', 3000);
        }
      }
    });
  }

  confirmManual() {
    this.api.confirmContractSigned().subscribe({
      next: () => {
        this.auth.updateLocalUser({ onboardingStep: 'active' });
        this.router.navigate(['/dashboard']);
      },
      error: () => { this.errorMsg = 'Erro ao confirmar.'; }
    });
  }
}
