// frontend/src/app/pages/indication-list/indication-list.component.ts
import { Component, OnInit } from '@angular/core';
import { ApiService } from '../../services/api.service';
import { STATUS_LABELS } from '../../models/interfaces';

@Component({
  selector: 'app-indication-list',
  template: `
    <div class="page-wrap">
      <div class="page-header">
        <h1>Minhas Indicações</h1>
        <p>Acompanhe o status de todas as suas indicações.</p>
      </div>

      <div class="filters">
        <button [class.active]="!filterStatus" (click)="filter('')">Todas ({{ total }})</button>
        <button *ngFor="let s of statusKeys" [class.active]="filterStatus===s" (click)="filter(s)"
          [style.border-color]="getColor(s)">
          {{ getLabel(s) }} ({{ stats[s] || 0 }})
        </button>
      </div>

      <div class="card" *ngIf="indications.length === 0 && !loading">
        <p class="empty">Nenhuma indicação encontrada. <a routerLink="/indication/new">Faça sua primeira indicação!</a></p>
      </div>

      <div class="table-wrap" *ngIf="indications.length > 0">
        <table>
          <thead>
            <tr><th>Data</th><th>Empresa</th><th>CNPJ</th><th>Segmento</th><th>Contato</th><th>Status</th></tr>
          </thead>
          <tbody>
            <tr *ngFor="let ind of indications">
              <td>{{ ind.createdAt | date:'dd/MM/yyyy' }}</td>
              <td class="bold">{{ ind.nomeEmpresa }}</td>
              <td>{{ ind.cnpj }}</td>
              <td>{{ ind.segmento }}</td>
              <td>{{ ind.nomeContato }}<br><small>{{ ind.emailContato }}</small></td>
              <td><span class="badge" [style.background]="getBg(ind.status)" [style.color]="getColor(ind.status)">{{ getLabel(ind.status) }}</span></td>
            </tr>
          </tbody>
        </table>
      </div>

      <div class="pagination" *ngIf="totalPages > 1">
        <button [disabled]="page<=1" (click)="goPage(page-1)">←</button>
        <span>Página {{ page }} de {{ totalPages }}</span>
        <button [disabled]="page>=totalPages" (click)="goPage(page+1)">→</button>
      </div>
    </div>
  `,
  styles: [`
    .page-wrap { max-width:1000px; margin:0 auto; padding:32px 24px 80px; }
    .page-header h1 { font-size:24px; color:#1B5E8C; margin:0 0 4px; }
    .page-header p { color:#666; font-size:14px; margin:0 0 20px; }
    .filters { display:flex; gap:8px; margin-bottom:20px; flex-wrap:wrap; }
    .filters button { padding:7px 16px; border:2px solid #D8DEE4; border-radius:20px; background:#fff; font-size:13px; font-weight:600; color:#666; cursor:pointer; }
    .filters button.active { border-color:#1B5E8C; background:#EAF2F8; color:#1B5E8C; }
    .card { background:#fff; border:1px solid #D8DEE4; border-radius:12px; padding:32px; text-align:center; }
    .empty { color:#888; font-size:15px; }
    .empty a { color:#1B5E8C; font-weight:600; }
    .table-wrap { overflow-x:auto; background:#fff; border:1px solid #D8DEE4; border-radius:12px; }
    table { width:100%; border-collapse:collapse; font-size:13px; }
    th { text-align:left; padding:12px; background:#F7F9FB; border-bottom:2px solid #D8DEE4; font-size:11px; text-transform:uppercase; color:#5A6672; letter-spacing:0.5px; }
    td { padding:10px 12px; border-bottom:1px solid #F2F3F4; color:#333; vertical-align:top; }
    td.bold { font-weight:600; }
    td small { color:#888; font-size:11px; }
    .badge { display:inline-block; padding:3px 10px; border-radius:12px; font-size:11px; font-weight:600; white-space:nowrap; }
    .pagination { display:flex; align-items:center; justify-content:center; gap:16px; margin-top:16px; }
    .pagination button { padding:8px 16px; border:1px solid #D8DEE4; border-radius:8px; background:#fff; cursor:pointer; font-weight:600; }
    .pagination button:disabled { opacity:0.4; cursor:default; }
  `]
})
export class IndicationListComponent implements OnInit {
  indications: any[] = [];
  total = 0;
  page = 1;
  totalPages = 1;
  stats: any = {};
  filterStatus = '';
  loading = false;
  statusKeys = ['nova', 'em_negociacao', 'sucesso', 'insucesso', 'pausada'];

  constructor(private api: ApiService) {}

  ngOnInit() { this.load(); }

  load() {
    this.loading = true;
    this.api.getIndications(this.page, 20, this.filterStatus || undefined).subscribe({
      next: (res) => {
        this.indications = res.indications;
        this.total = res.total;
        this.totalPages = res.totalPages;
        this.stats = res.stats;
        this.loading = false;
      },
      error: () => { this.loading = false; }
    });
  }

  filter(status: string) { this.filterStatus = status; this.page = 1; this.load(); }
  goPage(p: number) { this.page = p; this.load(); }
  getLabel(s: string) { return STATUS_LABELS[s]?.label || s; }
  getColor(s: string) { return STATUS_LABELS[s]?.color || '#333'; }
  getBg(s: string) { return STATUS_LABELS[s]?.bg || '#F2F3F4'; }
}

// frontend/src/pages/IndicationList.tsx
import { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import api from '../api/axios';
import { STATUS_LABELS } from '../utils/constants';

export default function IndicationList() {
  const [indications, setIndications] = useState<any[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [stats, setStats] = useState<any>({});
  const [filterStatus, setFilterStatus] = useState('');
  const [loading, setLoading] = useState(false);
  const statusKeys = ['nova', 'em_negociacao', 'sucesso', 'insucesso', 'pausada'];

  useEffect(() => { load(); }, [page, filterStatus]);

  function load() {
    setLoading(true);
    const params: any = { page, limit: 20 };
    if (filterStatus) params.status = filterStatus;
    api.get('/indication', { params }).then(res => {
      setIndications(res.data.indications);
      setTotal(res.data.total);
      setTotalPages(res.data.totalPages);
      setStats(res.data.stats);
    }).finally(() => setLoading(false));
  }

  function filter(s: string) { setFilterStatus(s); setPage(1); }

  return (
    <div style={styles.wrap}>
      <div style={styles.pageHeader}>
        <h1 style={styles.h1}>Minhas Indicações</h1>
        <p style={styles.sub}>Acompanhe o status de todas as suas indicações.</p>
      </div>
      <div style={styles.filters}>
        <button style={{ ...styles.filterBtn, ...(filterStatus === '' ? styles.filterActive : {}) }} onClick={() => filter('')}>Todas ({total})</button>
        {statusKeys.map(s => (
          <button key={s} style={{ ...styles.filterBtn, ...(filterStatus === s ? styles.filterActive : {}), borderColor: filterStatus === s ? STATUS_LABELS[s].color : '#D8DEE4' }} onClick={() => filter(s)}>
            {STATUS_LABELS[s].label} ({stats[s] || 0})
          </button>
        ))}
      </div>
      {indications.length === 0 && !loading ? (
        <div style={{ ...styles.card, textAlign: 'center' }}>
          <p style={{ color: '#888', fontSize: 15 }}>Nenhuma indicação encontrada. <Link to="/indication/new" style={{ color: '#1B5E8C', fontWeight: 600 }}>Faça sua primeira indicação!</Link></p>
        </div>
      ) : (
        <div style={styles.tableWrap}>
          <table style={styles.table}>
            <thead>
              <tr>
                <th style={styles.th}>Data</th><th style={styles.th}>Empresa</th><th style={styles.th}>CNPJ</th>
                <th style={styles.th}>Segmento</th><th style={styles.th}>Contato</th><th style={styles.th}>Status</th>
              </tr>
            </thead>
            <tbody>
              {indications.map((ind: any) => (
                <tr key={ind._id}>
                  <td style={styles.td}>{new Date(ind.createdAt).toLocaleDateString('pt-BR')}</td>
                  <td style={{ ...styles.td, fontWeight: 600 }}>{ind.nomeEmpresa}</td>
                  <td style={styles.td}>{ind.cnpj}</td>
                  <td style={styles.td}>{ind.segmento}</td>
                  <td style={styles.td}>{ind.nomeContato}<br /><small style={{ color: '#888', fontSize: 11 }}>{ind.emailContato}</small></td>
                  <td style={styles.td}>
                    <span style={{ display: 'inline-block', padding: '3px 10px', borderRadius: 12, fontSize: 11, fontWeight: 600, background: STATUS_LABELS[ind.status]?.bg, color: STATUS_LABELS[ind.status]?.color }}>
                      {STATUS_LABELS[ind.status]?.label || ind.status}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
      {totalPages > 1 && (
        <div style={styles.pagination}>
          <button style={styles.pageBtn} disabled={page <= 1} onClick={() => setPage(p => p - 1)}>←</button>
          <span>Página {page} de {totalPages}</span>
          <button style={styles.pageBtn} disabled={page >= totalPages} onClick={() => setPage(p => p + 1)}>→</button>
        </div>
      )}
    </div>
  );
}

const styles: Record<string, React.CSSProperties> = {
  wrap: { maxWidth: 1000, margin: '0 auto', padding: '32px 24px 80px' },
  pageHeader: { marginBottom: 20 },
  h1: { fontSize: 24, color: '#1B5E8C', margin: '0 0 4px' },
  sub: { color: '#666', fontSize: 14, margin: 0 },
  filters: { display: 'flex', gap: 8, marginBottom: 20, flexWrap: 'wrap' },
  filterBtn: { padding: '7px 16px', border: '2px solid #D8DEE4', borderRadius: 20, background: '#fff', fontSize: 13, fontWeight: 600, color: '#666', cursor: 'pointer' },
  filterActive: { borderColor: '#1B5E8C', background: '#EAF2F8', color: '#1B5E8C' },
  card: { background: '#fff', border: '1px solid #D8DEE4', borderRadius: 12, padding: 32 },
  tableWrap: { overflowX: 'auto', background: '#fff', border: '1px solid #D8DEE4', borderRadius: 12 },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: 13 },
  th: { textAlign: 'left', padding: 12, background: '#F7F9FB', borderBottom: '2px solid #D8DEE4', fontSize: 11, textTransform: 'uppercase', color: '#5A6672', letterSpacing: 0.5 },
  td: { padding: '10px 12px', borderBottom: '1px solid #F2F3F4', color: '#333', verticalAlign: 'top' },
  pagination: { display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 16, marginTop: 16 },
  pageBtn: { padding: '8px 16px', border: '1px solid #D8DEE4', borderRadius: 8, background: '#fff', cursor: 'pointer', fontWeight: 600 },
};
