// frontend/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  template: `
    <div class="auth-page">
      <div class="auth-card">
        <div class="auth-header">
          <h1>MAIS CHAT</h1>
          <p>Portal de Parceiros</p>
        </div>
        <h2>Entrar</h2>
        <form [formGroup]="form" (ngSubmit)="onSubmit()">
          <div class="field">
            <label>E-mail</label>
            <input type="email" formControlName="email" placeholder="seu@email.com">
          </div>
          <div class="field">
            <label>Senha</label>
            <input type="password" formControlName="password" placeholder="Sua senha">
          </div>
          <div class="error-msg" *ngIf="errorMsg">{{ errorMsg }}</div>
          <button type="submit" class="btn-primary" [disabled]="loading">
            {{ loading ? 'Entrando...' : 'Entrar' }}
          </button>
        </form>
        <p class="auth-link">Não tem conta? <a routerLink="/register">Cadastre-se</a></p>
      </div>
    </div>
  `,
  styles: [`
    .auth-page { min-height:100vh; display:flex; align-items:center; justify-content:center; background:linear-gradient(135deg,#1B5E8C 0%,#134263 100%); padding:24px; }
    .auth-card { background:#fff; border-radius:16px; padding:48px 40px; width:100%; max-width:420px; box-shadow:0 12px 40px rgba(0,0,0,0.2); }
    .auth-header { text-align:center; margin-bottom:32px; }
    .auth-header h1 { font-size:28px; color:#1B5E8C; letter-spacing:1px; margin:0; }
    .auth-header p { font-size:13px; color:#888; margin-top:2px; }
    h2 { font-size:20px; margin-bottom:24px; color:#2A2A2A; }
    .field { margin-bottom:16px; }
    .field label { display:block; font-size:12px; font-weight:600; color:#5A6672; text-transform:uppercase; letter-spacing:0.5px; margin-bottom:6px; }
    .field input { width:100%; padding:12px 16px; border:1.5px solid #D8DEE4; border-radius:8px; font-size:15px; background:#F7F9FB; transition:all 0.2s; box-sizing:border-box; }
    .field input:focus { outline:none; border-color:#1B5E8C; background:#fff; box-shadow:0 0 0 3px rgba(27,94,140,0.12); }
    .btn-primary { width:100%; padding:14px; background:#1B5E8C; color:#fff; border:none; border-radius:10px; font-size:16px; font-weight:700; cursor:pointer; transition:all 0.25s; margin-top:8px; }
    .btn-primary:hover { background:#134263; }
    .btn-primary:disabled { opacity:0.7; cursor:wait; }
    .error-msg { background:#FDEDEC; color:#C0392B; padding:10px 14px; border-radius:8px; font-size:13px; margin-bottom:12px; }
    .auth-link { text-align:center; margin-top:20px; font-size:14px; color:#666; }
    .auth-link a { color:#1B5E8C; font-weight:600; text-decoration:none; }
    .auth-link a:hover { text-decoration:underline; }
  `]
})
export class LoginComponent {
  form: FormGroup;
  loading = false;
  errorMsg = '';

  constructor(private fb: FormBuilder, private auth: AuthService, private router: Router) {
    if (this.auth.isLoggedIn) {
      this.redirectByRole();
    }
    this.form = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', Validators.required]
    });
  }

  onSubmit() {
    if (this.form.invalid) return;
    this.loading = true;
    this.errorMsg = '';

    this.auth.login(this.form.value.email, this.form.value.password).subscribe({
      next: () => {
        this.loading = false;
        this.redirectByRole();
      },
      error: (err) => {
        this.loading = false;
        this.errorMsg = err.error?.error || 'Erro ao fazer login.';
      }
    });
  }

  private redirectByRole() {
    const user = this.auth.currentUser;
    if (user?.role === 'admin') {
      this.router.navigate(['/admin']);
    } else if (user?.onboardingStep === 'company_data') {
      this.router.navigate(['/company-profile']);
    } else if (user?.onboardingStep === 'contract') {
      this.router.navigate(['/contract']);
    } else {
      this.router.navigate(['/dashboard']);
    }
  }
}

// frontend/src/pages/Login.tsx
import { useState, FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';

export default function Login() {
  const { login, isLoggedIn, user } = useAuth();
  const navigate = useNavigate();
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  if (isLoggedIn) {
    redirectByRole(user, navigate);
    return null;
  }

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (!email || !password) return;
    setLoading(true);
    setError('');
    try {
      await login(email, password);
      // After login, user state updates. Read from localStorage for redirect
      const u = JSON.parse(localStorage.getItem('mc_user') || '{}');
      redirectByRole(u, navigate);
    } catch (err: any) {
      setError(err.response?.data?.error || 'Erro ao fazer login.');
    } finally {
      setLoading(false);
    }
  }

  return (
    <div style={styles.page}>
      <div style={styles.card}>
        <div style={styles.header}>
          <h1 style={styles.brand}>MAIS CHAT</h1>
          <p style={styles.sub}>Portal de Parceiros</p>
        </div>
        <h2 style={styles.title}>Entrar</h2>
        <form onSubmit={handleSubmit}>
          <div style={styles.field}>
            <label style={styles.label}>E-mail</label>
            <input style={styles.input} type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="seu@email.com" />
          </div>
          <div style={styles.field}>
            <label style={styles.label}>Senha</label>
            <input style={styles.input} type="password" value={password} onChange={e => setPassword(e.target.value)} placeholder="Sua senha" />
          </div>
          {error && <div style={styles.error}>{error}</div>}
          <button type="submit" disabled={loading} style={styles.btn}>
            {loading ? 'Entrando...' : 'Entrar'}
          </button>
        </form>
        <p style={styles.link}>Não tem conta? <Link to="/register" style={styles.a}>Cadastre-se</Link></p>
      </div>
    </div>
  );
}

function redirectByRole(user: any, navigate: any) {
  if (!user) return;
  if (user.role === 'admin') navigate('/admin');
  else if (user.onboardingStep === 'company_data') navigate('/company-profile');
  else if (user.onboardingStep === 'contract') navigate('/contract');
  else navigate('/dashboard');
}

const styles: Record<string, React.CSSProperties> = {
  page: { minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'linear-gradient(135deg, #1B5E8C 0%, #134263 100%)', padding: 24 },
  card: { background: '#fff', borderRadius: 16, padding: '48px 40px', width: '100%', maxWidth: 420, boxShadow: '0 12px 40px rgba(0,0,0,0.2)' },
  header: { textAlign: 'center', marginBottom: 32 },
  brand: { fontSize: 28, color: '#1B5E8C', letterSpacing: 1, margin: 0 },
  sub: { fontSize: 13, color: '#888', marginTop: 2 },
  title: { fontSize: 20, marginBottom: 24, color: '#2A2A2A' },
  field: { marginBottom: 16 },
  label: { display: 'block', fontSize: 12, fontWeight: 600, color: '#5A6672', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 6 },
  input: { width: '100%', padding: '12px 16px', border: '1.5px solid #D8DEE4', borderRadius: 8, fontSize: 15, background: '#F7F9FB', boxSizing: 'border-box' },
  btn: { width: '100%', padding: 14, background: '#1B5E8C', color: '#fff', border: 'none', borderRadius: 10, fontSize: 16, fontWeight: 700, cursor: 'pointer', marginTop: 8 },
  error: { background: '#FDEDEC', color: '#C0392B', padding: '10px 14px', borderRadius: 8, fontSize: 13, marginBottom: 12 },
  link: { textAlign: 'center', marginTop: 20, fontSize: 14, color: '#666' },
  a: { color: '#1B5E8C', fontWeight: 600, textDecoration: 'none' },
};
